name = "Kod"
grammar = "kod"
path_suffixes = ["kod"]
line_comments = ["// "]
autoclose_before = ",;:.})]>"
tab_size = 4

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
